In [36]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [57]:
df = pd.read_csv('tf.csv')
print(df.shape)
df.head()

(50, 1826)

,name,61546,generation,72541,glenn,guerr,nam,marri,happiness,hop,...,lying,matt,primarily,friendship,quality,thom,168937,onlinereal,application,carp
0,http://quotes.toscrape.com/,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1,http://quotes.toscrape.com/tag/simile/,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,http://quotes.toscrape.com/tag/reading/,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,http://quotes.toscrape.com/tag/truth/,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
4,http://quotes.toscrape.com/tag/books/,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0

# pesado
$w = tf \cdot idf\$

$w :=$ pesado de cada elemento en la tabla

$tf :=$ es el elemento en la columna y fila

$idf = log\frac{N}{n_k} $

N = total de documentos

$n_k$ = numero de documentos donde aparece el stem

In [42]:
N = df.shape[0] # N

In [50]:
stems = df.columns[1:]
results = pd.DataFrame([], columns=df.columns)
def is_present(column, number=0):
    return (column > number).sum()
n_k = df.drop(columns='name').apply(is_present)

id_k = np.log2(N/n_k) 
id_k.hasnans

False

In [54]:
tf_idf = df[stems].mul(id_k, axis=1)
tf_idf.head()

,61546,generation,72541,glenn,guerr,nam,marri,happiness,hop,dugald,...,lying,matt,primarily,friendship,quality,thom,168937,onlinereal,application,carp
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.321928,0.0,2.643856,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.321928,0.0,0.000000,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.321928,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.643856,0.0,0.0,0.321928,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.643856,0.0,0.000000,0.0,0.0,0.0,0.0

In [59]:
print(type(n_k))
df[ df['lying'] >0 ]

<class 'pandas.core.series.Series'>

,name,61546,generation,72541,glenn,guerr,nam,marri,happiness,hop,...,lying,matt,primarily,friendship,quality,thom,168937,onlinereal,application,carp
3,http://quotes.toscrape.com/tag/truth/,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
8,http://quotes.toscrape.com/tag/humor/,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
27,http://quotes.toscrape.com/tag/humor/page/1/,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
49,https://www.goodreads.com/quotes,1,0,1,0,0,0,0,1,2,...,1,3,0,4,0,0,1,0,0,1

# Query

In [63]:
query = 'It is our choices, Harry, that show what we truly are, far more than our abilities'

In [64]:
query = re.split(r"[^a-z0-9]+", query)
query = process_text.ProcessData('query', query) #Procesamos la consulta aplicando stopwords y stems

9
9
	*****

In [67]:
query.frequency

{'choic': 1,
 'arry': 1,
 'that': 1,
 'show': 1,
 'what': 1,
 'truly': 1,
 'mor': 1,
 'than': 1,
 'abiliti': 1}

In [80]:
new_row = {key: [ query.frequency.get(key, 0) ] for key in df.columns[1:]} 
new_row['name'] = 'query'
new_row = pd.DataFrame(new_row)
new_row = new_row[stems].mul(id_k, axis=1)
new_row['choic']

0    3.643856
Name: choic, dtype: float64

In [84]:
pd.concat([tf_idf, new_row])

,61546,generation,72541,glenn,guerr,nam,marri,happiness,hop,dugald,...,lying,matt,primarily,friendship,quality,thom,168937,onlinereal,application,carp
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.643856,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.321928,0.000000,0.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.897353,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.058894,3.643856,0.000000,...,0.000000,2.321928,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.643856,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.321928,0.000000,0.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.321928,0.000000,1.609640,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.321928,0.000000,1.609640,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.321928,0.000000,1.609640,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,5.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.643856,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.000000,4.643856,0.000000,0.000000,0.000000,4.643856,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,5.287712,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,0.000000,4.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,16.931569,0.000000,0.000000,5.643856,5.643856,0.000000
36,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.321928,0.000000,0.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.058894,3.643856,0.000000,...,0.000000,2.321928,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
40,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,5.643856,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.321928,0.000000,2.643856,0.000000,0.000000,0.000000,0.000000
47,0.000000,0.000000,0.000000,0.000000,5.643856,37.150850,5.643856,0.000000,0.000000,5.643856,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.643856,0.000000,...,0.000000,2.321928,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,5.643856,0.000000,5.643856,0.000000,0.000000,0.000000,0.000000,4.058894,7.287712,0.000000,...,3.643856,6.965784,0.000000,1.287712,0.000000,0.000000,5.643856,0.000000,0.000000,5.643856
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000